# Site settings
site_name: Mizz Media Pro
logo_url: https://placehold.co/100x100/png?text=MizzMediaPro

theme: minimal-mistakes-jekyll

title: MizzMediaPro
description: "Social Media Management and AI Solutions"

author:
  name: Nana Johnson
  email: your-email@example.com
  bio: "Helping clothing brands grow with AI & social media."

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

navigation:
  - title: Home
    url: /#home
  - title: About
    url: /#about
  - title: Services
    url: /#services
  - title: Contact
    url: /#contact

collections:
  pages:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "single"

sass:
  style: compressed

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..6
  header_permalink: false

# Load custom CSS for styling
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      custom_css: "/assets/css/custom.css"

  
  # To disable permalink icons completely, try:
  # (depending on theme/plugin, sometimes)
  # header_permalink: false
