backend:
  name: github
  repo: Goldielockz30/my-smmm-site
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

media_library:
  name: default

collections:
  - name: "pages"
    label: "Pages"
    folder: "_pages"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
