backend:
  name: github
  repo: Goldielockz30/my-smmm-site
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

media_library:
  name: default

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Services"
        name: "services"
        file: "services.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
